---
title: "Synth View alternative modelling"
author: "MIKE MERRY"
date: "7/24/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(modelr)
library(rpart)
library(AUC)

df.1000.raw <- read.csv('./../data/processed/synthetic_view_test_0001000.csv')

test <- read.csv('./../data/processed/synthetic_view_test.csv') %>%
  mutate(is.female = as.logical(is.female),
         smoking = as.logical(smoking),
         diabetes = as.logical(diabetes),
         dead = as.logical(dead))

df.1000 <- df.1000.raw %>%
  select(is.female,
        ag_age,
        pt_bps,
        smoking,
        pt_tc_hdl_ratio,
        diabetes,
        dead) %>%
  mutate(is.female = as.logical(is.female),
         smoking = as.logical(smoking),
         diabetes = as.logical(diabetes),
         dead = as.logical(dead))
```

```{r}
df.1000 %>%
  head()
```

```{r}
df.1000 %>%
  group_by(diabetes) %>%
  summarise(n=n())
```

```{r}
test %>%
  group_by(imp_hxdiab) %>%
  summarise(n=n())
```



```{r}
linear <- lm(dead ~ is.female + 
               log(ag_age) + 
               log(ag_age)*is.female +
               log(pt_bps) + 
               smoking + 
               log(pt_tc_hdl_ratio) + 
               diabetes +
               diabetes*is.female, 
             data = df.1000)
```

```{r}
linear %>%
  summary()
```

```{r}
test$preds <- predict(linear, test)
```

```{r}
test %>%
  group_by(dead) %>%
  summarise(n=n(),
            mean(preds),
            sd(preds))
```
```{r}
test %>%
  ggplot(aes(dead, preds)) +
  geom_boxplot()
```

```{r}

test %>%
  ggplot(aes(sample=preds)) +
  stat_qq() +
  geom_qq_line()
```

```{r}
df.1000 %>%
  group_by(is.female, dead) %>%
  summarise(n=n(),
            nDiab = sum(diabetes),
            prop.Diab = nDiab/n)
```

```{r}
df.1000 %>%
  group_by(dead) %>%
  summarise(n=n())
```


```{r}
test %>%
  ggplot(aes(preds, fill=dead)) +
  geom_histogram()
```


```{r}
plot(roc(test$preds, as.factor(test$dead)))
```

```{r}
roc.test <- roc(test$preds, as.factor(test$dead))
```

```{r}
auc(roc.test)
```




risk.score.five.year <- function(is.female, age, sbp, smokes, chol.ratio, diabetes){
  b.0 <- 18.8144
  b.1 <- -1.2146
  b.2 <- -1.8443
  b.3 <- 0.3668
  b.4 <- -1.4032
  b.5 <- -0.3899
  b.6 <- -0.5390
  b.7 <- -0.3036
  b.8 <- -0.1697
  
  theta.0 = 0.6536
  theta.1 = -0.2402
  
  mu <- b.0 + 
    b.1 * is.female +
    b.2 * log(age) + 
    b.3 * log(age) * is.female +
    b.4 * log(sbp) +
    b.5 * smokes +
    b.6 * log(chol.ratio) +
    b.7 * diabetes +
    b.8 * diabetes * is.female

