---
title: "Comparison analysis"
author: "MIKE MERRY"
date: '2022-09-25'
output: html_document
---

```{r setup, include=FALSE}
  
knitr::opts_chunk$set(echo = TRUE)
require("tidyverse")
library(pROC)
experiment_sha <- "24c00ce9" # 24088379
experiment_sha <- "b53e57d1" 
experiment_sha <- "24088379"
experiment_sha <- "b4c86de1"
experiment_sha <- "4bcfe941"
sha_file <- "./sha_file.json"
sha_doc <- rjson::fromJSON(file=sha_file)
config_doc <- rjson::fromJSON(file="./all_data_benchmarking_experiment_config.json")
experiment_sha <- sha_doc$sha
experiment_sha <- "3d382b80"
# dataset_name <- "GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1"

# dataset_name <- "breast_cancer_wisconsin"
codename <- config_doc$experiment$codename
```

```{r}
experiment_sha
```


# Data ingest

```{r}
# results <- read_csv("./../../data/experiments/tests/data/resultsDatabase.csv")
# results <- read_csv("./../../data/experiments/tests/data/resultsDatabase_mlrig.csv")
results <- read_csv("./../../../mount_remote_phd/processed/resultsDatabase.csv")

# results %>% filter(experimentSha == experiment_sha) %>%
#   select(-value) %>%View

```
```{r}
dataset_name <- "tic_tac_toe"

y_test <- read_csv(str_glue("./../../../mount_remote_phd/processed//",codename,"/",experiment_sha, "/",dataset_name,"/y_test.csv"))
```
```{r}
y_test %>%
  glimpse()
```


```{r}
results %>%
  filter(dataset==dataset_name,
         experimentSha==experiment_sha) %>% glimpse
```

```{r}
predictions <- results %>%
  filter(str_detect(measurementType, "predict"),
         experimentSha == experiment_sha,
         dataset==dataset_name)
predictions$value <- map(predictions$value, jsonlite::fromJSON)
predictions %>% 
  glimpse
```

```{r}
compute_auc <- function(preds){
    my_tib<-tibble(y_test, preds)
    my_roc <- roc(my_tib, y, preds)
    return(as.numeric(my_roc$auc[[1]]))
}
compute_roc <- function(preds){
    my_tib<-tibble(y_test, preds)
    return(roc(my_tib, y, preds))
}
```



```{r}
predictions$auc <-map(predictions$value, compute_auc)
predictions$roc <- map(predictions$value, compute_roc)

predictions <- predictions %>% 
  rowwise() %>%
  mutate(
      sensitivities = list(roc$sensitivities),
     specificities = list(roc$specificities))
# 
# predictions %>%
#   select(starts_with("s")) %>%
#   glimpse()
```



```{r}

long_preds <- predictions %>%
  unnest_longer(c("sensitivities","specificities")) %>%
  group_by(measurementType,iteration,sensitivities) %>%
  summarise(specificities = max(specificities))
```



```{r}
long_preds %>% 
  # filter(measurementType != "propneat_retrain_prediction")%>%
  ggplot(aes(1-specificities, 
             sensitivities, 
             group=interaction(measurementType,iteration),
             color=measurementType)) +
  geom_line(alpha=.4) +
  geom_segment(aes(x=0, y=0, xend=1, yend=1), colour="black")
  
```

```{r}
long_preds %>%
  filter( grepl("propne",measurementType) ) %>%
  ggplot(aes(1-specificities, 
             sensitivities, 
             group=interaction(measurementType,iteration),
             color=measurementType)) +
  geom_line(alpha=0.4) +
  geom_segment(aes(x=0, y=0, xend=1, yend=1), colour="black")
  
```

```{r}
long_preds %>%
  filter( grepl("propne",measurementType) ) %>%
  mutate(opacity = if_else(measurementType == "propneat_prediction", 1, 1))%>%
  ggplot(aes(1-specificities, 
             sensitivities, 
             group=interaction(measurementType,iteration),
             color=measurementType,
             alpha=opacity)) +
  geom_line() +
  facet_wrap(iteration%/%100~.) +
  geom_segment(aes(x=0, y=0, xend=1, yend=1), colour="black")
  
```
```{r}
# results %>%
#   view("results")
```


```{r}
predictions %>% 
  select(-value,
         -experimentName,
         -dataset,
         -params)
```


```{r}
predictions %>%
  select(measurementType,
         iteration,
         auc) %>%
  view("Scores_mlrig")
```

```{r}
predictions %>%
  select(measurementType,
         value,
         auc) %>%
  mutate(auc = as.numeric(auc)) %>%
  group_by(measurementType) %>%
  summarise(mean_auc = mean(auc))
```


```{r}
results %>% glimpse
```

```{r}
results %>% 
  filter(measurementType == "skippiness") %>%
  group_by(experimentSha) %>%
  summarise(avg_skippy = mean(as.numeric(value))) 
```



